remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
gem "github-pages", group: :jekyll_plugins

title: Yudong Hu
description: A graduate student from UoA with a keen interest in AI
# logo: path/to/image.png

show_downloads: "true"
